### ISSUE TITLE
Division of Work - Milestone 1

### ISSUE THREAD

**Issue by ofer-m** [UBC-MDS/DSCI_522_Group405#3]
- [x] Github set up - Ofer

- [x] Team work Contract - Ofer

- [x] Code of Conduct, Contributing file, License - Jacky

- [x] Project Proposal - Ofer makes an outline, Jacky writes it

- [x] Download Script - Anand

- [x] EDA - Ofer starts, Anand finishes
